### ISSUE TITLE
Missing name from link to function in another package

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/snorkel#1]
Using `rd_fn_other_pkg()` on `package::function` results in `\code{\link[package]{function}}` as expected. 

But if you don't highlight any text before using the function, you get: `\code{\link[}}`, i.e. `]{` are missing from the middle.

Perhaps want a separate print statement when text hasn't first been selected.

**Comment by FinancialRADDeveloper** [comment]
I have just noticed this too.
